[build]
command = """
    scripts/build-glean-metadata.py
    npm run build
    if [ "$STORYBOOK" ]; then
      npm run build-storybook
      mv storybook-static public/storybook
    fi
"""
environment = { PYTHON_VERSION = "3.7" }
publish = "public"

[context.production]
  [context.production.environment]
  CONTEXT = "production"

[[redirects]]
  from = "https://glean-dictionary.netlify.app"
  to = "https://dictionary.telemetry.mozilla.org"
  status = 301
  force = true
